version: "3.0" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  redis: # 서비스 명
    image: redis # 사용할 이미지
    restart: always
    container_name: redis-test # 컨테이너 이름 설정
    ports:
      - "6379:6379" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- Redis 기본 포트는 6379
    volumes:
      - /path/to/redis/data:/data # -v 옵션 (데이터 디렉토리 마운트 설정)

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander-test
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

# docker-compose -f docker-compose-redis.yml up -d 실행
