spring:
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/my_schema?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0197
    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/my_schema?serverTimezone=UTC&characterEncoding=UTF-8
  #    username: root
  #    password: 0197
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL;NON_KEYWORDS=USER
  #    username: sa
  #    password:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    generate-ddl: true
    show-sql: true
    open-in-view: true
    dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql