spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa
    password:
  #    url: jdbc:mysql://localhost:3306/my_schema?serverTimezone=UTC&characterEncoding=UTF-8
  #    username: root
  #    password: 0197

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always