#Quartz
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_schema?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0197
  #    sql:
  #      init:
  #        data-locations: classpath:tables_mysql.sql
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    generate-ddl: false
    dialect: org.hibernate.dialect.MysqlDialect

  quartz:
    scheduler-name: MyQuartzScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
      schema: classpath:tables_mysql.sql
      platform: mysql
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    auto-startup: true
  # quartz 에 대한 porperty 정보들은 quartz.properties 파일로 이동