spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gkehdrn95@netand.co.kr
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
