spring:
  profiles:
    active: local

jasypt:
  encryptor:
    #    password: world // ????? ????? ???? ??x
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64

data:
  origin: wrong
  encrypted: wrong