POST http://localhost:8080/v1/first
Content-Type: application/json

{
  "name": "first",
  "negativeInt": -1
}

###
POST http://localhost:8080/v1/first
Content-Type: application/json

{
  "name": "first",
  "negativeInt": 1
}

###
POST http://localhost:8080/v1/second
Content-Type: application/json

{
  "name": "second",
  "max10": 5
}

###
POST http://localhost:8080/v1/second
Content-Type: application/json

{
  "name": "second",
  "max10": 11
}