spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_scheme?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: acacian
    password: acacian
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: true
