version: "3.0"
services:
  db:
    image: mariadb
    restart: always
    container_name: mariadb-test
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=0197
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/Shared/data/mariadb-test:/var/lib/mariadb

# docker-compose -f docker-compose-mariadb.yml up -d 실행